fullsalvo update

diff --git a/.bin/rhisk b/.bin/rhisk
--- a/.bin/rhisk
+++ b/.bin/rhisk
@@ -1,22 +1,125 @@
 #!/usr/bin/env bash
 # Script Name: rhisk
 # Written by fullsalvo
+# Combined with scripts written by Ethan Chan - https://github.com/metakirby5
 # Loads whizkers templates including those from subfolders
 
-out=""
-direc="$HOME/.config/whizkers/variable_sets"
+################
+# Declarations #
+################
 
-for i in "$@"; do
-    if [[ -e "${direc}/${i}.yaml" ]]; then
-	out+="${i} "
-    else
-	check=$(find $direc -name $i.yaml)
-	if [[ ! -z $check ]]; then
-	    check="${check##${direc}/}"
-	    check="${check%%.yaml}"
-	    out+="${check} "
-	fi
+# None for now
+
+#############
+# Functions #
+#############
+
+reload-desktop ()
+{
+    # Reload the desktop
+
+    killall compton dunst
+
+    i3-msg 'restart' &>/dev/null &
+    compton &>/dev/null &
+    dunst &>/dev/null &
+
+    xrdb -merge ~/.Xresources &>/dev/null &
+    tmux source-file ~/.tmux.conf &>/dev/null &
+
+    # Reload colors, fonts, etc.
+    for pts in /dev/pts/*; do
+	(echo -n "$(use-xresources < ~/.Xresources)" > $pts) 2>/dev/null &
+    done &
+}
+
+wzk ()
+{
+    yes 2>/dev/null | relink-config >/dev/null
+
+    if [ "$?" -ne 0 ]; then
+	echo 'relink-config FAILED'
+	exit 1
     fi
-done
 
-wzk $out
+    if [ "$#" -eq 0 ]; then
+	whizkers -e >/dev/null
+    else
+	whizkers -e "$@" >/dev/null
+    fi
+
+    [ "$?" -ne 0 ] && exit 1
+
+    reload-desktop
+    [ "$#" -ne 0 ] && sleep 0.5
+
+    exit 0
+}
+
+theme ()
+{
+    out=""
+    direc="$HOME/.config/whizkers/variable_sets"
+    for i in "$@"; do
+	if [[ -e "${direc}/${i}.yaml" ]]; then
+	    out+="${i} "
+	else
+	    check=$(find $direc -name $i.yaml)
+	    if [[ ! -z $check ]]; then
+		check="${check##${direc}/}"
+		check="${check%%.yaml}"
+		out+="${check} "
+	    else
+		printf "Template \'${i}\' doesn't exist. Please choose a valid template.\n"
+		exit 1
+	    fi
+	fi
+    done
+
+    wzk $out
+    exit 0
+}
+
+options ()
+{
+    out=$(whizkers -l)
+    printf "Options:\n"
+    for line in $out; do
+	printf "%2s${line##*\/}\n"
+    done
+}
+
+usage ()
+{
+    clear
+    more <<-'HELP'
+rhisk - whizkers theme switch script
+Usage:
+  rhisk [ optional args... ] - Rhisk
+
+Help Options:
+  -?, -h                  Show help options
+Theme Options:
+  -o                      Show theme options
+HELP
+}
+
+###########
+# Options #
+###########
+
+while getopts ':ho?:' option; do
+    case $option in
+	o)
+	    options
+	    exit
+	    ;;
+	? | h)
+	    usage
+	    exit
+	    ;;
+    esac
+done
+shift $((OPTIND-1))
+
+theme "$@"
diff --git a/.bin/wallshuf b/.bin/wallshuf
--- a/.bin/wallshuf
+++ b/.bin/wallshuf
@@ -1,11 +1,24 @@
 #!/usr/bin/env bash
 
-declare interval
+################
+# Declarations #
+################
+declare program
+declare blurvalue
+declare tintvalue
+declare duration=60
 declare recursive=false
+declare verbose=false
+declare oneshot=false
+declare bold="$(tput bold)"
+declare italic="$(tput sitm)"
+declare reset="$(tput sgr0)"
 declare -a images
 declare -a search_dirs
-declare verbose=false
 
+#############
+# Functions #
+#############
 err() {
 	echo -e "\e[31m$1\e[0m" >&2
 }
@@ -15,38 +28,151 @@ die() {
 	exit 1
 }
 
-while :; do
-	case "$1" in
-		-v|--verbose)
+inpath() {
+	type "$1" &> /dev/null
+}
+
+usage() {
+	more <<-'HELP'
+wallshuffle.sh - wallpaper shuffling script
+Usage: wallshuffle.sh [OPTION]... IMAGE OR DIRECTORY...
+
+-d NUMBER  - Set duration (in seconds) between wallpaper changes (default: 60)
+-p PROGRAM - Set which program to use; either 'hsetroot' or 'feh'
+-o         - Set a random wallpaper once and quit
+-r         - Recursively find images in directories
+-h         - Print this help information
+-v         - Enable verbose output
+
+The following options only work if hsetroot is used
+-b NUMBER  - Set blur radius
+-t NUMBER  - Set tint value (#FFFFFF is no change)
+HELP
+}
+
+###########
+# Options #
+###########
+while getopts ':vrd:hob:p:t:' option; do
+	case "$option" in
+		h)
+			usage
+			exit
+			;;
+		p)
+			program="$OPTARG"
+			;;
+		b)
+			blurvalue="$OPTARG"
+			;;
+		t)
+			tintvalue="$OPTARG"
+			;;
+		o)
+			unset oneshot
+			;;
+		v)
 			unset verbose
-			shift
 			;;
-		-r|--recursive)
+		r)
 			unset recursive
-			shift
 			;;
-		-i|--interval)
-			if [[ "$2" =~ ^[0-9]+$ ]]; then
-				interval="$2"
-				shift 2
+		d)
+			if [[ "$OPTARG" =~ ^[0-9]+$ ]]; then
+				duration="$OPTARG"
+			fi
+			;;
+		\?)
+			err "-$OPTARG is not a valid option"
+			;;
+	esac
+done
+shift $((OPTIND-1))
+
+# If the program was specified, make sure it's valid...
+if [[ -n "$program" ]]; then
+	case "$program" in
+		hsetroot)
+			if ! inpath hsetroot; then
+				echo 'Specified program 'hsetroot' is not in $PATH'
+				if inpath feh; then
+					echo 'Falling back to feh'
+					program="feh"
+				else
+					echo 'feh not found in $PATH either'
+					exit 1
+				fi
+			fi
+			;;
+		feh)
+			if ! inpath feh; then
+				echo 'Specified program 'feh' is not in $PATH'
+				if inpath hsetroot; then
+					echo 'Falling back to hsetroot'
+					program="hsetroot"
+				else
+					echo 'hsetroot not found in $PATH either'
+					exit 1
+				fi
 			fi
 			;;
 		*)
-			if [[ -d "$1" ]]; then
-				search_dirs+=( "$1" )
-				shift
-			elif [[ -f "$1" ]]; then
-				if [[ "$1" =~ \.(jpeg|jpg|png)$ ]]; then
-					images+=( "$1" )
-				elif [[ -z $verbose ]]; then
-					err "$1 is not an acceptable file, must be png or jpg"
-				fi
-				shift
-			else
-				break
-			fi
+			echo 'Valid arguments for -p are "hsetroot" and "feh"'
+			exit 1
 			;;
 	esac
+# ...otherwise, determine the program automatically
+else
+	if inpath hsetroot; then
+		program="hsetroot"
+	elif inpath feh; then
+		program="feh"
+	else
+		echo "This script depends on either hsetroot or feh"
+		exit 1
+	fi
+fi
+
+# If no images are provided, show usage and exit
+if [[ -z "$1" ]]; then
+	usage
+	exit 1
+fi
+
+if [[ -z $verbose ]]; then
+	echo "Using $program"
+fi
+
+if [[ -n "$blurvalue" ]]; then
+	# Currently equivalent to [[ -n "$blurvalue" && "$program" == feh ]]
+	# But this will make adding support for more programs easier
+	case $program in
+		feh)
+			err "-b can only be used with hsetroot"
+			;;
+	esac
+fi
+
+if [[ -n "$tintvalue" ]]; then
+	case $program in
+		feh)
+			err "-t can only be used with hsetroot"
+			;;
+	esac
+fi
+
+for argument in $@; do
+	if [[ -d "$1" ]]; then
+		search_dirs+=( "$1" )
+		shift
+	elif [[ -f "$1" ]]; then
+		if [[ "$1" =~ \.(jpeg|jpg|png)$ ]]; then
+			images+=( "$1" )
+		elif [[ -z $verbose ]]; then
+			err "$1 is not an acceptable file, must be png or jpg"
+		fi
+		shift
+	fi
 done
 
 if (( ${#search_dirs[@]} > 0 )); then
@@ -56,19 +182,41 @@ if (( ${#search_dirs[@]} > 0 )); then
 	done
 fi
 
-[[ -z $verbose ]] && echo "${#images[@]} images found"
-
 if (( ${#images[@]} < 1 )); then
 	die 'No images found'
-elif (( ${#images[@]} == 1 )); then
-	feh --bg-fill ${images[@]}
+elif (( ${#images[@]} == 1 )) && [[ -z $verbose ]]; then
+	echo "1 image found"
+elif (( ${#images[@]} > 1 )) && [[ -z $verbose ]]; then
+	echo "${#images[@]} images found"
+fi
+
+if (( ${#images[@]} == 1 )) || [[ -z "$oneshot" ]]; then
+	if [[ -z "$oneshot" ]]; then
+		mapfile -t images < <(printf '%s\n' "${images[@]}" | shuf)
+	fi
+	[[ -z $verbose ]] && echo "Loading ${images[0]}"
+	case $program in
+		hsetroot)
+			hsetroot -fill "${images[0]}" -blur ${blurvalue:-0} -tint ${tintvalue:-#ffffff}
+			;;
+		feh)
+			feh --bg-fill "${images[0]}"
+			;;
+	esac
 	exit
 fi
 
 while true; do
 	printf '%s\n' "${images[@]}" | shuf | while IFS= read -r image; do
 		[[ -z $verbose ]] && echo "Loading $image"
-		feh --bg-fill "$image"
-		sleep ${interval:-60}
+		case $program in
+			hsetroot)
+				hsetroot -fill "$image" -blur ${blurvalue:-0} -tint ${tintvalue:-#ffffff}
+				;;
+			feh)
+				feh --bg-fill "$image"
+				;;
+		esac
+		sleep $duration
 	done
 done
